# Generated by Django 5.0.14 on 2026-09-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('incremento_muscular', 'Incremento muscular'), ('recomposicion_corporal', 'Recomposición corporal'), ('mantenimiento', 'Mantenimiento')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField()),
                ('peso_actual', models.FloatField()),
                ('peso_objetivo', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_seguimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True)),
                ('peso_actualizacion', models.FloatField()),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='seguimiento.seguimiento')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
