# Generated by Django 5.0.14 on 2026-09-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquina', models.CharField(max_length=150)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_reparacion', 'En Reparación')], default='activo', max_length=15)),
            ],
        ),
    ]
