# Generated by Django 5.0.14 on 2026-09-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('core', 'Core'), ('cardio', 'Cardio')], max_length=10),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='equipamiento',
            field=models.CharField(blank=True, choices=[('maquina', 'Máquina'), ('mancuernas', 'Mancuernas'), ('barra', 'Barra'), ('polea', 'Polea'), ('peso_corporal', 'Peso corporal'), ('otro', 'Otro')], max_length=15),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('compuesto', 'Compuesto'), ('aislamiento', 'Aislamiento')], max_length=12),
        ),
    ]
