# Generated by Django 5.0.14 on 2026-09-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('objetivo', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('adaptativo', 'Adaptativo'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('ejercicios', models.ManyToManyField(blank=True, related_name='rutinas', to='ejercicios.ejercicio')),
                ('plan_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='seguimiento.seguimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
                ('tipo_rutina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='rutinas.tiporutina')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('enfoque', models.CharField(max_length=100)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='rutinas.rutina')),
            ],
        ),
    ]
