# Generated by Django 5.0.14 on 2026-09-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_ejercicio_categoria_ejercicio_equipamiento_and_more'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='objetivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('series', models.PositiveSmallIntegerField()),
                ('repeticiones', models.CharField(max_length=15)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_rutinas', to='ejercicios.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rutinas.rutina')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
